name: "🚩 tests"

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  tests:
    name: 🚩 Tests
    runs-on: ubuntu-latest
    steps:
      - name: ☄️ checkout
        uses: actions/checkout@v2
      - name: 🐱‍🏍 node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: 📦 install dependencies
        run: yarn
      - name: 🚩 run tests
        run: yarn test
